import type {
  User,
  ClassGroup,
  Lesson,
  AttendanceRecord,
  StudentFeedback,
  TeacherEvaluation,
  TeacherReport,
  PerformanceGoal,
} from '../types';

export const mockUsers: User[] = [
  {
    id: 'admin-1',
    name: 'Mônica Almeida',
    email: 'monica@etus.com.br',
    role: 'admin',
    createdAt: '2024-01-01',
  },
  {
    id: 'teacher-1',
    name: 'Carlos Silva',
    email: 'carlos.silva@etus.com.br',
    role: 'teacher',
    createdAt: '2024-01-01',
  },
  {
    id: 'student-1',
    name: 'Ana Costa',
    email: 'ana.costa@etus.com.br',
    role: 'student',
    createdAt: '2024-01-15',
  },
  {
    id: 'student-2',
    name: 'Pedro Santos',
    email: 'pedro.santos@etus.com.br',
    role: 'student',
    createdAt: '2024-01-15',
  },
  {
    id: 'student-3',
    name: 'Juliana Lima',
    email: 'juliana.lima@etus.com.br',
    role: 'student',
    createdAt: '2024-02-01',
  },
  {
    id: 'student-4',
    name: 'Rafael Oliveira',
    email: 'rafael.oliveira@etus.com.br',
    role: 'student',
    createdAt: '2024-02-01',
  },
  {
    id: 'student-5',
    name: 'Mariana Ferreira',
    email: 'mariana.ferreira@etus.com.br',
    role: 'student',
    createdAt: '2024-02-15',
  },
];

export const mockClassGroups: ClassGroup[] = [
  {
    id: 'class-1',
    name: 'Inglês Básico - Manhã',
    description: 'Turma de inglês básico, foco em conversação e gramática fundamental',
    teacherId: 'teacher-1',
    teacherName: 'Carlos Silva',
    schedule: 'Terça e Quinta, 8h-9h30',
    studentIds: ['student-1', 'student-2', 'student-3'],
    createdAt: '2024-01-01',
    active: true,
  },
  {
    id: 'class-2',
    name: 'Inglês Intermediário - Manhã',
    description: 'Turma de inglês intermediário, foco em business English',
    teacherId: 'teacher-1',
    teacherName: 'Carlos Silva',
    schedule: 'Segunda e Quarta, 8h-9h30',
    studentIds: ['student-4', 'student-5'],
    createdAt: '2024-01-01',
    active: true,
  },
];

export const mockLessons: Lesson[] = [
  {
    id: 'lesson-1',
    classGroupId: 'class-1',
    date: '2025-05-06',
    topic: 'Present Perfect vs Simple Past',
    description: 'Diferenças de uso entre Present Perfect e Simple Past com exercícios práticos',
    teacherId: 'teacher-1',
    createdAt: '2025-05-06',
  },
  {
    id: 'lesson-2',
    classGroupId: 'class-1',
    date: '2025-05-08',
    topic: 'Business Vocabulary - Meetings',
    description: 'Vocabulário essencial para reuniões em inglês',
    teacherId: 'teacher-1',
    createdAt: '2025-05-08',
  },
  {
    id: 'lesson-3',
    classGroupId: 'class-1',
    date: '2025-05-13',
    topic: 'Listening Practice - TED Talks',
    description: 'Prática de listening com TED Talks sobre tecnologia',
    teacherId: 'teacher-1',
    createdAt: '2025-05-13',
  },
  {
    id: 'lesson-4',
    classGroupId: 'class-2',
    date: '2025-05-05',
    topic: 'Advanced Grammar - Conditionals',
    description: 'Condicionais avançadas: mixed conditionals e inversões',
    teacherId: 'teacher-1',
    createdAt: '2025-05-05',
  },
  {
    id: 'lesson-5',
    classGroupId: 'class-2',
    date: '2025-05-07',
    topic: 'Presentation Skills',
    description: 'Como fazer apresentações profissionais em inglês',
    teacherId: 'teacher-1',
    createdAt: '2025-05-07',
  },
];

export const mockAttendance: AttendanceRecord[] = [
  {
    id: 'att-1',
    lessonId: 'lesson-1',
    classGroupId: 'class-1',
    date: '2025-05-06',
    records: [
      { studentId: 'student-1', studentName: 'Ana Costa', present: true },
      { studentId: 'student-2', studentName: 'Pedro Santos', present: true },
      { studentId: 'student-3', studentName: 'Juliana Lima', present: false, notes: 'Reunião com cliente' },
    ],
    createdAt: '2025-05-06',
  },
  {
    id: 'att-2',
    lessonId: 'lesson-2',
    classGroupId: 'class-1',
    date: '2025-05-08',
    records: [
      { studentId: 'student-1', studentName: 'Ana Costa', present: true },
      { studentId: 'student-2', studentName: 'Pedro Santos', present: false, notes: 'Viagem a trabalho' },
      { studentId: 'student-3', studentName: 'Juliana Lima', present: true },
    ],
    createdAt: '2025-05-08',
  },
  {
    id: 'att-3',
    lessonId: 'lesson-3',
    classGroupId: 'class-1',
    date: '2025-05-13',
    records: [
      { studentId: 'student-1', studentName: 'Ana Costa', present: true },
      { studentId: 'student-2', studentName: 'Pedro Santos', present: true },
      { studentId: 'student-3', studentName: 'Juliana Lima', present: true },
    ],
    createdAt: '2025-05-13',
  },
  {
    id: 'att-4',
    lessonId: 'lesson-4',
    classGroupId: 'class-2',
    date: '2025-05-05',
    records: [
      { studentId: 'student-4', studentName: 'Rafael Oliveira', present: true },
      { studentId: 'student-5', studentName: 'Mariana Ferreira', present: true },
    ],
    createdAt: '2025-05-05',
  },
  {
    id: 'att-5',
    lessonId: 'lesson-5',
    classGroupId: 'class-2',
    date: '2025-05-07',
    records: [
      { studentId: 'student-4', studentName: 'Rafael Oliveira', present: false, notes: 'Doente' },
      { studentId: 'student-5', studentName: 'Mariana Ferreira', present: true },
    ],
    createdAt: '2025-05-07',
  },
];

export const mockStudentFeedback: StudentFeedback[] = [
  {
    id: 'fb-1',
    studentId: 'student-1',
    studentName: 'Ana Costa',
    classGroupId: 'class-1',
    month: 4,
    year: 2025,
    rating: 5,
    contentRating: 4,
    teacherRating: 5,
    comments: 'As aulas estão excelentes! O professor explica muito bem.',
    suggestions: 'Gostaria de mais prática de conversação.',
    createdAt: '2025-04-30',
  },
  {
    id: 'fb-2',
    studentId: 'student-2',
    studentName: 'Pedro Santos',
    classGroupId: 'class-1',
    month: 4,
    year: 2025,
    rating: 4,
    contentRating: 4,
    teacherRating: 5,
    comments: 'Bom conteúdo, estou aprendendo bastante.',
    suggestions: 'Mais exercícios de listening.',
    createdAt: '2025-04-30',
  },
  {
    id: 'fb-3',
    studentId: 'student-4',
    studentName: 'Rafael Oliveira',
    classGroupId: 'class-2',
    month: 4,
    year: 2025,
    rating: 5,
    contentRating: 5,
    teacherRating: 5,
    comments: 'Aulas muito produtivas, estou evoluindo rápido.',
    suggestions: 'Simulações de reuniões em inglês.',
    createdAt: '2025-04-30',
  },
];

export const mockTeacherEvaluations: TeacherEvaluation[] = [
  {
    id: 'eval-1',
    teacherId: 'teacher-1',
    studentId: 'student-1',
    studentName: 'Ana Costa',
    classGroupId: 'class-1',
    bimester: 1,
    year: 2025,
    speaking: 4,
    listening: 3,
    reading: 4,
    writing: 3,
    participation: 5,
    overallScore: 3.8,
    strengths: 'Excelente participação em aula, boa pronúncia.',
    areasToImprove: 'Precisa melhorar writing e estrutura de textos.',
    comments: 'Ana está progredindo bem e mostra muito interesse.',
    createdAt: '2025-04-15',
  },
  {
    id: 'eval-2',
    teacherId: 'teacher-1',
    studentId: 'student-2',
    studentName: 'Pedro Santos',
    classGroupId: 'class-1',
    bimester: 1,
    year: 2025,
    speaking: 3,
    listening: 4,
    reading: 4,
    writing: 4,
    participation: 3,
    overallScore: 3.6,
    strengths: 'Boa compreensão de textos e gramática.',
    areasToImprove: 'Precisa praticar mais a conversação e perder a timidez.',
    comments: 'Pedro tem bom potencial mas precisa participar mais.',
    createdAt: '2025-04-15',
  },
  {
    id: 'eval-3',
    teacherId: 'teacher-1',
    studentId: 'student-3',
    studentName: 'Juliana Lima',
    classGroupId: 'class-1',
    bimester: 1,
    year: 2025,
    speaking: 3,
    listening: 3,
    reading: 3,
    writing: 2,
    participation: 4,
    overallScore: 3.0,
    strengths: 'Muito dedicada e sempre faz as atividades.',
    areasToImprove: 'Todas as habilidades precisam de reforço, principalmente writing.',
    comments: 'Juliana está no início mas mostra muita dedicação.',
    createdAt: '2025-04-15',
  },
  {
    id: 'eval-4',
    teacherId: 'teacher-1',
    studentId: 'student-4',
    studentName: 'Rafael Oliveira',
    classGroupId: 'class-2',
    bimester: 1,
    year: 2025,
    speaking: 4,
    listening: 4,
    reading: 5,
    writing: 4,
    participation: 4,
    overallScore: 4.2,
    strengths: 'Excelente leitura e compreensão de textos complexos.',
    areasToImprove: 'Pronúncia de algumas palavras específicas.',
    comments: 'Rafael está pronto para avançar para o nível avançado.',
    createdAt: '2025-04-15',
  },
];

export const mockTeacherReports: TeacherReport[] = [
  {
    id: 'report-1',
    teacherId: 'teacher-1',
    teacherName: 'Carlos Silva',
    classGroupId: 'class-1',
    classGroupName: 'Inglês Básico - Manhã',
    bimester: 1,
    year: 2025,
    summary: 'A turma do básico mostrou boa evolução no primeiro bimestre. Os alunos estão engajados e participam ativamente.',
    achievements: 'Todos os alunos conseguem se apresentar em inglês, fazer perguntas básicas e entender comandos simples.',
    challenges: 'A frequência oscilou em algumas semanas devido a demandas de trabalho. Writing ainda é um ponto fraco geral.',
    recommendations: 'Recomendo manter a frequência mínima de 75% para todos os alunos. Implementar exercícios de writing semanais.',
    nextSteps: 'No próximo bimestre, focar em Business English básico e simulações de situações reais de trabalho.',
    createdAt: '2025-04-15',
  },
];

export const mockPerformanceGoals: PerformanceGoal[] = [
  {
    id: 'goal-1',
    userId: 'student-1',
    userName: 'Ana Costa',
    title: 'Certificação B2 em Inglês',
    description: 'Alcançar nível B2 no CEFR até o final do ano.',
    category: 'Inglês',
    targetDate: '2025-12-31',
    status: 'in_progress',
    progress: 40,
    createdAt: '2025-01-15',
    updatedAt: '2025-05-01',
  },
  {
    id: 'goal-2',
    userId: 'student-2',
    userName: 'Pedro Santos',
    title: 'Apresentar projeto em inglês',
    description: 'Ser capaz de apresentar um projeto completo em inglês para stakeholders internacionais.',
    category: 'Inglês',
    targetDate: '2025-09-30',
    status: 'in_progress',
    progress: 25,
    createdAt: '2025-01-15',
    updatedAt: '2025-05-01',
  },
  {
    id: 'goal-3',
    userId: 'student-4',
    userName: 'Rafael Oliveira',
    title: 'Liderar reunião em inglês',
    description: 'Conduzir reuniões semanais com o time internacional de forma autônoma.',
    category: 'Inglês',
    targetDate: '2025-06-30',
    status: 'in_progress',
    progress: 70,
    createdAt: '2025-01-15',
    updatedAt: '2025-05-01',
  },
];
